DROP TABLE STAGE;
DROP TABLE ENTREPRISE;
DROP TABLE PROGRAMME;

CREATE TABLE PROGRAMME(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Nom VARCHAR(255) NOT NULL
);

CREATE TABLE ENTREPRISE(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Nom VARCHAR(255) NOT NULL
);

CREATE TABLE STAGE(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Etat VARCHAR(255) NOT NULL CHECK (ETAT IN ('DISPONIBLE','COMPLETE')),
	NomPoste VARCHAR(255) NOT NULL,
	Salaire FLOAT,
	DateDebut DATE NOT NULL,
	DateFin DATE NOT NULL,
	EntrepriseId INT REFERENCES ENTREPRISE(Id),
	ProgrammeId INT REFERENCES PROGRAMME(Id)
);

INSERT INTO PROGRAMME VALUES(
	'Analyste programmeur'
);

INSERT INTO PROGRAMME VALUES(
	'Big data'
);

INSERT INTO PROGRAMME VALUES(
	'Concepteur de base de données'
);

INSERT INTO PROGRAMME VALUES(
	'Intelligence artificielle'
);

INSERT INTO ENTREPRISE VALUES(
	'Harris Computers'
);

INSERT INTO ENTREPRISE VALUES(
	'Kezber'
);

INSERT INTO ENTREPRISE VALUES(
	'CGI'
);

INSERT INTO ENTREPRISE VALUES(
	'Desjardins'
);

INSERT INTO STAGE VALUES(
	'DISPONIBLE',
	'Programmeur C#',
	52000,
	CONVERT(datetime, '2020/02/15', 111),
	CONVERT(datetime, '2020/05/15', 111),
	1,
	1
);

INSERT INTO STAGE VALUES(
	'DISPONIBLE',
	'Programmeur Java',
	5700,
	CONVERT(datetime, '2020/01/12', 111),
	CONVERT(datetime, '2020/04/15', 111),
	2,
	1
);

INSERT INTO STAGE VALUES(
	'DISPONIBLE',
	'Concepteur Sql',
	67000,
	CONVERT(datetime, '2020/02/19', 111),
	CONVERT(datetime, '2020/05/21', 111),
	3,
	3
);